<a href="https://colab.research.google.com/github/leejyy/New/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
np_city=np.array(['NYC','LA','Miami','Houston'])

In [3]:
np_city.ndim

1

In [6]:
np_city_with_state=np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])

In [7]:
np_city_with_state.ndim

2

In [8]:
a=[10,15,16]
b=[12,13,14]
np_a=np.array(a)
np_b=np.array(b)
np_a+np_b

array([22, 28, 30])

In [9]:
np_sqrt=np.sqrt([2,4,9,16])
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [10]:
from numpy import pi
np.cos(0)

1.0

In [11]:
np.sin(pi/2)

1.0

In [12]:
np.cos(pi)

-1.0

In [13]:
np.floor([1.5,1.4,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  1.,  2.,  3.,  1., -1., -2.])

In [14]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])